In [1]:
import numpy as np

In [2]:
def sigmoid(x,deriv= False):
	if(deriv==True):
	    return (x*(1-x))

	return (1/(1+np.exp(-x)))

In [6]:
ip=np.array([[0,0,1],                  #l0 is 4*3 matrix
             [0,1,1], 
             [1,0,1],
             [1,1,1]])
y=np.array([[0],[1],[1],[0]])                       #y is 4*1 matrix

np.random.seed(98)
syn0 = 2*np.random.random((3,4)) - 1        #3*4
syn1 = 2*np.random.random((4,1)) - 1        #4*1
#l1=np.empty((4,4))

In [8]:
for i in range(60000):
    l0=ip
    l1= sigmoid(np.dot(l0,syn0))               #4*4
    l2= sigmoid(np.dot(l1,syn1))               #4*1

    l2_error= y - l2                             #4*1
    if (i% 10000) == 0:
        print("Error:"+str(np.mean(np.abs((l2_error)))))
    
    l2_error_delta=l2_error*sigmoid(l2,deriv=True)     #4*1
    l1_error=l2_error_delta.dot(syn1.T)             #4*4
    #l1_error= np.dot(l2_error_delta,(syn1.T))
    l1_error_delta=l1_error*sigmoid(l1,deriv=True)  #4*4
    syn1+= ((l1.T).dot(l2_error_delta))
    syn0+= ((l0.T).dot(l1_error_delta))
    
print(l2)

Error:0.003321422972313478
Error:0.003047355573567719
Error:0.002829418363535455
Error:0.0026509333933636557
Error:0.0025013935607413177
Error:0.0023738146761523296
[[0.0018171 ]
 [0.99770081]
 [0.998032  ]
 [0.00296917]]


In [72]:
syn0

array([[-0.69811218, -0.6930143 ,  0.96572467,  0.81047221],
       [-0.63222202, -0.47333119, -0.34264388,  0.29125542],
       [-0.50373272,  0.2537294 ,  0.14394531,  0.24067438]])

In [42]:
l1=sigmoid(np.dot(l0,syn0))
l2=sigmoid(np.dot(l1,syn1))  
l2_err=y-l2
q=l2_err*sigmoid(l2,True)
l1_error = q.dot(syn1.T)
l1_error_delta=l1_error*sigmoid(l1,deriv=True)
l1_error_delta
syn1 +=l1.T.dot(l2_error_delta)
w=l0.T.dot(l1_error_delta)
l2_error

#np.dot(l1,syn

array([[-0.42516045],
       [ 0.4130212 ],
       [ 0.49001899],
       [-0.47662072]])

In [107]:
l1=sigmoid(10,True)
l1

-90

array([[ 8, 15]])